### ISSUE TITLE
Not in pypi?

### ISSUE THREAD

**Issue by oren-z0** [monty888/monstr#8]
Package not listed in pypi.org.
`pip install` doesn't work.

**Comment by oren-z0** [comment]
LOL, I tried to install the package, opened the ticked, refreshed the page, and the pip instructions vanished. I thought I was hallucinating...

**Comment by monty888** [comment]
You must have done it when I finally decided to remove that! Someone did get it to install from some dev pip url - though even then it was a bit of a pain because a lot of the dependencies don't exist there.

Anyway it's pretty easy to do just via cloning and then pip install . So for now that seems acceptable.

Sent from ProtonMail mobile

-------- Original Message --------
